name: multiselect_nested
description: A simple multiselect dropdown with nested options support for Flutter.
version: 1.1.0
homepage: https://github.com/GiuseppeSperanza/multiselect_nested
# author: Giuseppe Speranza<giuseppesperanza.dev>

environment:
  sdk: '>=2.18.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

